# Generated by Django 3.1.3 on 2020-11-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201109_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.DeleteModel(
            name='PostPicture',
        ),
    ]
